codon = {
    "UUU":"F", "UUC":"F", "UUA":"L", "UUG":"L",
    "UCU":"S", "UCC":"S", "UCA":"S", "UCG":"S",
    "UAU":"Y", "UAC":"Y", "UAA":"*", "UAG":"*",
    "UGU":"C", "UGC":"C", "UGA":"*", "UGG":"W",
    "CUU":"L", "CUC":"L", "CUA":"L", "CUG":"L",
    "CCU":"P", "CCC":"P", "CCA":"P", "CCG":"P",
    "CAU":"H", "CAC":"H", "CAA":"Q", "CAG":"Q",
    "CGU":"R", "CGC":"R", "CGA":"R", "CGG":"R",
    "AUU":"I", "AUC":"I", "AUA":"I", "AUG":"M",
    "ACU":"T", "ACC":"T", "ACA":"T", "ACG":"T",
    "AAU":"N", "AAC":"N", "AAA":"K", "AAG":"K",
    "AGU":"S", "AGC":"S", "AGA":"R", "AGG":"R",
    "GUU":"V", "GUC":"V", "GUA":"V", "GUG":"V",
    "GCU":"A", "GCC":"A", "GCA":"A", "GCG":"A",
    "GAU":"D", "GAC":"D", "GAA":"E", "GAG":"E",
    "GGU":"G", "GGC":"G", "GGA":"G", "GGG":"G"}


#here we calculate the frequency of each amino acid codon

freq = {}

c_freq = list(codon.values())
s_freq = set(c_freq)

for i in s_freq:
    freq[i] = c_freq.count(i)



#here we calculate the probablity of each amino acid codon 

prob = 1

s = 'MESYNCAPPAHRPVERIVHCKEMLIKWYQIMNPPVNVSLRDLRCWDSWFTLGDCWHQYKAKQVVRGGIAGIFQESMCEQMEMCPPDFEAANDIVDSILNGTETKNMWKSKESGKWPYAYDYPSFMVEGWYQLREKICWIAWWKHQKEYMSAQSIQVIIDPDCAEYEIWGIEQNHIGECHVGPAFISYFVLEGQCTPGLYRKKSPAFYSNHRIITRAIQWDILLNEIQGATIHGHLDLVYWQTHKYSEWAPAIASNFSVFCSTPMQDGGLFGPTSKVQPVRWTKKADSCQFLEGRGAAIDADHKPGSMWQMSDMYCFQEWNQDLQGYACHWMWWTCECVFQMYYSNLIKNFIQISGQGNWPTPIAMHAGTWAFVISKKHQSQAFVLVPQENQMVRMGFKHHKGVYWAAWFWIDIRPMNWSLQDEIILCMKASMGHMDQNGIHGRIVYDGRTPQEFYRHQSYWYWTGIFWTSLFVQRWCVFRKMMWIQIIKDDIHEWFENEMEKISEYYNPWRGNLEPYLSDGQFCPGYKMRCYMFSWEENYHWRFLMWQIPQSGYHMGNCYHYMAIKIEHRCKFLKRPDSWQTMWCDDNRCKMESNIEVMPHPHRFHNGWAFKSTYWRKVSWPWFRFLQSITEQYRHYVHGHTSRQYALTQAVRNHRKDSNVRSMMITMLWYEATDYYLPGYSHIPKDFHSENWVPPMYPRPMFIHVHNDPNCPVFYRHGLSAFEHFCFEGTTSPCWMVHRNDNSHSMIWRMLNWWRYAAMTLWVANMSGHCCRYMRRYAAYAYKVNMAVAKCNLVCLWNAWPENVSERKVCISTCFQQVHEHQRKVYSIHWWSNRQVTALQRVVWPPLNFAAKGEDMGDVFEYAWHGCYPPPQCADYHRAFIQKYFFQFPAEQVKTTKRILMNRECYARFHDQNVDFDHAYRHKWCTKCQALRNGMNDCRVKRFLCTHSYCSGLHHDDCVTYGSFAKHPETYGIHYNYPIYEQDADGPEWSDWMCAKAKS*'

for i in s:
    prob = (prob*freq[i])%1000000

print(prob)