def palind(DNA):
	cDNA=""
	DNA_dict = {"A":"T","T":"A","C":"G","G":"C"}
	for i in DNA:
		cDNA+=DNA_dict[i]
	return (cDNA[::-1])


file = open("st.txt")

s = file.readlines()

seq = "CGCGCTCGTATCATGCCTCTGTTTGCTTATGATACTAACCGCCCCGACGCGTTAACAAAA GAGAAATACCTTGCAAGGTGTCACTTCCTTCAAACACCACTAGGAATATGCCTAATCCAA GTCGTTACTAAGTAGCCGTACTGATAATTGGATTTACTCCGGCACTGTAACTTCAGGGAC CGACGGCGCCTAAAGTTCTCTCACACGGAGTAGGGAGCATTGTAGCTAACGAGACGGCAA TTGATTGGAACGGGCACGGTAGTATAATTATTTGGTAACAGACTAGCATCTTTGTATAGA TACCATTGGCTTAGAAAGGAGCGGCCCATGCTGTGTGTCAATAATGGCAATTAAATAGAC CACGATAAGCGGGTTGGAAGTGATAAGTTAGTTATGCATCAAGCTTACTCCAATATTAAG GTTACGCTACAGTTGGGAAAAATTACGCAATCTCTATCCTCGGACGTCCGAACCTTCTTG CTACATGACCAACGATTCTATGATAGTCCGAAATCCGTCGAATGAGTGGGTTGGCCCAGG GAGACCACTCAGGAATGCCTCTCGCGACGATCTTCGGATACACCTAGAGATGTGCAAGTC CCTCATGTATTTGAGACCTGGTCCGACTGATTGATTTCCCTTGTGCTAGCTGTAGCATAG GCATGCCCACAAGACCCAAGAACGTGGATTTTCGGGTTGGGTTGCCCTTACGGCAATATG CCGTTGCATCCTCGGTTGACTTAGGACATCTGGACGCCGTTCACATCAGCGGACGACACC GACACTGTATTGGACTGATGAGTCTTCAACGTCGGGTGCCCATATTGAACCCTTACTGCA GGATCAACTTATGACTAGCTATTGCTCCATTAATGTCTTTTTAGAAAGCTTGAAACGAAT AGAGGATCGACATGTCACGTCCCTGCATAT"
seq = seq.replace(" ","")
sett=[]
for i in range(len(seq)):
	for j in range(4,13):
		if (seq[i:i+j] == palind(seq[i:i+j]) and (len(seq[i:i+j]) in range(4,13))):
			if seq[i:i+j] not in sett:
				sett.append((i+1,len(seq[i:i+j])))



sett1=set(sett)
for i,j in sett1:
	print(i,j)


